# Use an official Python runtime as a parent image #doesn't have to match Eva's Env exactly
# Use an official Python runtime as a parent image
FROM python:3.7-slim


# Install curl
RUN apt-get update && apt-get install -y curl libcurl4-openssl-dev

# Set environment variables #default for py project
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Set up virtual environment
#RUN virtualenv venv
#RUN /bin/bash -c "source venv/bin/activate"

# Install project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run app.py when the container launches
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
