// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9LMeCggalTofCZ15yhkiMmHZIQyK_478',
    appId: '1:1093945962106:web:e089ba7eba5d7ae05555c3',
    messagingSenderId: '1093945962106',
    projectId: 'campusalert-ece498',
    authDomain: 'campusalert-ece498.firebaseapp.com',
    storageBucket: 'campusalert-ece498.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8gPDmrklPmbFwbeCmSb30FOJdv0eGzXI',
    appId: '1:1093945962106:android:ba27eec334f1ed225555c3',
    messagingSenderId: '1093945962106',
    projectId: 'campusalert-ece498',
    storageBucket: 'campusalert-ece498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf1sc_D6dssBt-h72FFO0O5pETAfe-UTs',
    appId: '1:1093945962106:ios:ce9e7dd3d7794f755555c3',
    messagingSenderId: '1093945962106',
    projectId: 'campusalert-ece498',
    storageBucket: 'campusalert-ece498.appspot.com',
    iosClientId: '1093945962106-r1grfeeu9kvl9pf7e5t58i79nbrqmpdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf1sc_D6dssBt-h72FFO0O5pETAfe-UTs',
    appId: '1:1093945962106:ios:1f561e97c3a8d1475555c3',
    messagingSenderId: '1093945962106',
    projectId: 'campusalert-ece498',
    storageBucket: 'campusalert-ece498.appspot.com',
    iosClientId: '1093945962106-mpr91a8s0b5gjjgmqr3lsfbnqd50b8ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusalert.RunnerTests',
  );

  static const FirebaseOptions adminPost = FirebaseOptions( //has photo, allow user content filtering, 
  // latency ++ when scale up and more crtieria to filter, thus use individual database
  apiKey: "AIzaSyB9LMeCggalTofCZ15yhkiMmHZIQyK_478",
  authDomain: "campusalert-ece498.firebaseapp.com",
  projectId: "campusalert-ece498",
  storageBucket: "campusalert-ece498.appspot.com",
  messagingSenderId: "1093945962106",
  appId: "1:1093945962106:web:e089ba7eba5d7ae05555c3"
  );
}
