name: campusalert
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-89.0.dev <4.0.0'

dependencies:
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  provider: ^6.0.0
  rxdart: ^0.27.7
  http: ^1.1.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.0.7
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  drift_db_viewer: ^2.0.0
  cached_network_image: ^3.3.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.13.0
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/overpass/Overpass-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/overpass/Overpass-VariableFont_wght.ttf
