name: campusalert
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-89.0.dev <4.0.0'

dependencies:
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  provider: ^6.0.0
  rxdart: ^0.27.7
  http: ^0.13.4
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/overpass/Overpass-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/overpass/Overpass-VariableFont_wght.ttf
