# Generated by Django 3.2.20 on 2024-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
