# Generated by Django 3.2.20 on 2024-02-24 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_auto_20240126_2257'),
        ('adminPost', '0002_blogpost_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='emergency.building'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='crime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='emergency.crime'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='emergency.floor'),
        ),
    ]
