# Generated by Django 3.2.20 on 2023-10-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('begin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beginning_buildings', to='emergency.coordinate')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_buildings', to='emergency.coordinate')),
            ],
        ),
    ]
