# Generated by Django 3.2.20 on 2023-10-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='begin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beginning', to='emergency.coordinate'),
        ),
        migrations.AlterField(
            model_name='building',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending', to='emergency.coordinate'),
        ),
    ]
