# Generated by Django 3.2.20 on 2023-10-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_auto_20231001_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='layout_image',
            field=models.ImageField(blank=True, null=True, upload_to='layout_images/'),
        ),
    ]
