# Generated by Django 3.2.20 on 2023-10-02 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_building_layout_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('begin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begin', to='emergency.coordinate')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='emergency.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='FloorLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('layout_image', models.ImageField(blank=True, null=True, upload_to='layout_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.AddField(
            model_name='floor',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='emergency.floorlayout'),
        ),
    ]
