# Generated by Django 4.2.2 on 2023-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="meow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("iswp", models.BooleanField(default=False)),
                ("search_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
