# Generated by Django 4.2.2 on 2023-07-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0003_coordinate_crime_location_report_delete_meow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinate", name="Floor", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="report",
            name="Report_number",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
