# Generated by Django 4.2.2 on 2023-07-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0004_alter_coordinate_floor_alter_report_report_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="coordinate", name="Floor",),
        migrations.AddField(
            model_name="location", name="Floor", field=models.IntegerField(default=0),
        ),
    ]
