# Generated by Django 3.2.20 on 2023-07-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_auto_20230709_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='coordinate',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='crime',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='crime',
            old_name='Type',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Building',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Campus',
            new_name='campus',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Coordinate',
            new_name='coordinate',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Floor',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Crime',
            new_name='crime',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Emergency',
            new_name='emergency',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Report_number',
            new_name='report_number',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Status',
            new_name='status',
        ),
    ]
