# Generated by Django 3.2.20 on 2023-07-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_auto_20230714_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.DeleteModel(
            name='coordinate',
        ),
        migrations.DeleteModel(
            name='crime',
        ),
        migrations.DeleteModel(
            name='location',
        ),
        migrations.DeleteModel(
            name='report',
        ),
    ]
