# Generated by Django 3.2.20 on 2024-02-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_auto_20231105_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='coordinate',
            options={'ordering': ['longitude', 'latitude']},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['building', 'floor_number']},
        ),
        migrations.AlterModelOptions(
            name='floorlayout',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['building', 'floor', 'room']},
        ),
        migrations.AlterModelOptions(
            name='roomedge',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='roomnode',
            options={'ordering': ['floor', 'name']},
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syncThreat', models.CharField(choices=[('fire', 'Fire'), ('attacker', 'Attacker'), ('storm', 'Storm')], max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.building')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.floor')),
                ('roomNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.roomnode')),
            ],
        ),
    ]
