# Generated by Django 3.2.20 on 2024-01-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_auto_20231105_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='coordinate',
            options={'ordering': ['longitude', 'latitude']},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['building', 'floor_number']},
        ),
        migrations.AlterModelOptions(
            name='floorlayout',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['building', 'floor', 'room']},
        ),
        migrations.AlterModelOptions(
            name='roomedge',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='roomnode',
            options={'ordering': ['floor', 'name']},
        ),
    ]
