# Generated by Django 3.2.20 on 2024-02-20 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_auto_20240220_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='building',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.building'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='floor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.floor'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='roomNode',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.roomnode'),
        ),
    ]
