# Generated by Django 3.2.20 on 2024-02-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_auto_20240220_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='syncThreat',
            field=models.CharField(choices=[('fire', 'Fire'), ('attacker', 'Attacker'), ('storm', 'Storm')], default=None, max_length=10, null=True),
        ),
    ]
