# Generated by Django 3.2.20 on 2024-03-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_auto_20240126_2257'),
        ('emergency', '0007_auto_20240222_0358'),
    ]

    operations = [
    ]
