# Generated by Django 3.2.20 on 2024-03-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_auto_20240305_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='alarm',
            new_name='alarm1',
        ),
    ]
